### ISSUE TITLE
#TK01 Definir requerimientos que dejarán reflejados en el IEEE830

### ISSUE THREAD

**Issue by MarielaGomez** [MarielaGomez/PrimerProyectoFullStack#1]

**Comment by MarielaGomez** [comment]
Registrar la Especificación de Requerimientos mediante la [documentación IEEE830] (subirlo en una carpeta de GitHub en la rama main)

**Comment by yan0106** [comment]
Se trabajó en el archivo "Documentación IEEE830" de la wiki.
