### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by MarielaGomez** [MarielaGomez/PrimerProyectoFullStack#11]
El objetivo del sprint 1 será tener los avances en el modelo de bases de datos, diseño del mismo y estructura web con la implementación de etiquetas HTML- CSS"

**Comment by yan0106** [comment]
trabajamos con estilos de bootstrap en archivo layout.html

**Comment by MarielaGomez** [comment]
Se carga modelo de base de datos y scripts de APP

**Comment by EliasCe00** [comment]
Agrego diseño y estilos de la sección de contacto del sitio web
